services:
  ouster:
    image: ros2-ouster-driver
    build:
      context: .
      args:
        - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    command: >
      sensor_hostname:=192.168.200.2 viz:=false
